const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const followingUserSchema = new mongoose.Schema({
  friend: {
    type: String,
    required: true
  },
  friendId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
});

const schema = new mongoose.Schema({
  username: {
    type: String,
    required: [true, 'Path `username` is required.'],
    unique: [true, 'username already exists']
  },
  email: {
    type: String,
    required: [true, 'Path `email` is required.'],
    unique: [true, 'email already exists']
  },
  passwordHash: {
    type: String,
    required: true
  },
  soundcloudUsername: {
    type: String
  },
  bandcampUsername: {
    type: String
  },
  followedUsers: [followingUserSchema]
}, {
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      delete ret.passwordHash;
    }
  }
});

schema.virtual('drives', {
  ref: 'Drive',
  localField: '_id',
  foreignField: 'userRef'
});

schema.virtual('friends', {
  ref: 'User',
  localField: 'friendId',
  foreignField: '_id'
});

schema.statics.addFriend = function(friend, user) {
  return Promise.all([
    this.findOne({ username: friend }),
    this.findById(user)
  ])
    .then(([friend, user]) => {
      const friendToAdd = {
        friend: friend.username,
        friendId: friend._id
      };
      user.followedUsers.push(friendToAdd);
      return this.findOneAndUpdate({
        _id: user._id
      }, user, { new: true });
    });
};


schema.virtual('password').set(function(password) {
  const hash = bcrypt.hashSync(password, Number(process.env.HASH_TIMES) || 14);
  this.passwordHash = hash;
});

schema.statics.authorize = async function({ email, password }) {
  const user = await this.findOne({ email });
  if(!user) {
    const error = new Error('Invalid email/password');
    error.status = 401;
    throw error;
  }
  const matchingPassword = await bcrypt.compare(password, user.passwordHash);
  if(!matchingPassword) {
    const error = new Error('Invalid email/password');
    error.status = 401;
    throw error;
  }
  return user;
};

schema.statics.findByToken = function(token) {
  try {
    const { payload } = jwt.verify(token, process.env.APP_SECRET);
    return Promise.resolve(this.hydrate(payload));
  } catch(e) {
    return Promise.reject(e);
  }
};

schema.methods.authToken = function() {
  const token = jwt.sign({ payload: this.toJSON() }, process.env.APP_SECRET, { expiresIn: '24h' });
  return token;
};

module.exports = mongoose.model('User', schema);


// User
// -id (generated by mongoose)
// -email **
// -username **
// -password (salt, hash)
// -profile image
// -bio
// -followed users
